name: Integração Contínua Portfolio 

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Instalar Dependências
        run: |
          npm install 

      - name: Executar ESLint
        run: npm run lint

      - name: Rodar Testes
        run: npm run test