name: Integração Contínua Cypress Tests AmazonAPP

on:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  cypress-tests-desktop:
    needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Instalar Dependências
        run: npm ci

      - name: Rodar Testes Cypress
        run: npm run test
